# Generated by Django 5.2.5 on 2025-11-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Mark as Read')),
                ('replied', models.BooleanField(default=False, verbose_name='Replied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Degree/Certificate Title', help_text='e.g., BSc Computer Science', max_length=200, verbose_name='Degree/Certificate Title')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution Name')),
                ('location', models.CharField(blank=True, max_length=140, verbose_name='Location')),
                ('degree_level', models.CharField(choices=[('hs', 'High School'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('cert', 'Certification'), ('other', 'Other')], default='other', max_length=12, verbose_name='Degree Level')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('ongoing', models.BooleanField(default=False, help_text='Check if still studying', verbose_name='Currently Studying')),
                ('grade_or_gpa', models.CharField(blank=True, max_length=80, verbose_name='Grade/GPA')),
                ('summary', models.TextField(blank=True, help_text='Short description, projects, honors, or relevant coursework', verbose_name='Summary')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='education/logos/', verbose_name='Institution Logo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('visible', models.BooleanField(default=True, verbose_name='Show on Website')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('job', 'Job Experience'), ('skill', 'Technical Skill')], default='job', help_text='Job Experience ya Technical Skill?', max_length=20, verbose_name='Type')),
                ('title', models.CharField(default='Title', help_text='Job Title (e.g., Full Stack Developer) OR Skill Name (e.g., Python)', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Job description OR Skill description', verbose_name='Description')),
                ('company', models.CharField(blank=True, default='Company Name', help_text='Only for Job Experience', max_length=200, verbose_name='Company Name')),
                ('location', models.CharField(blank=True, help_text='Only for Job Experience', max_length=200, verbose_name='Location')),
                ('start_date', models.DateField(blank=True, help_text='Only for Job Experience', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Only for Job Experience', null=True, verbose_name='End Date')),
                ('ongoing', models.BooleanField(default=False, help_text='Only for Job Experience', verbose_name='Currently Working Here')),
                ('proficiency', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], help_text='Only for Technical Skills', max_length=50, verbose_name='Proficiency Level')),
                ('category', models.CharField(blank=True, help_text='e.g., Programming, Framework, Database (for Skills)', max_length=100, verbose_name='Category')),
                ('icon', models.ImageField(blank=True, help_text='Company logo OR Skill icon', null=True, upload_to='experience/', verbose_name='Logo/Icon')),
                ('visible', models.BooleanField(default=True, verbose_name='Show on Website')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience / Skill',
                'verbose_name_plural': 'Experiences / Skills',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Project Title', help_text='Project title', max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(blank=True, help_text='Project description', verbose_name='Description')),
                ('path', models.CharField(blank=True, help_text='Static image path (e.g., images/project1.jpg)', max_length=500, verbose_name='Image Path')),
                ('demo', models.URLField(blank=True, help_text='Live demo link (optional)', max_length=500, null=True, verbose_name='Demo URL')),
                ('github', models.URLField(blank=True, help_text='GitHub repository link (optional)', max_length=500, null=True, verbose_name='GitHub URL')),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Upcoming', 'Upcoming')], max_length=50, null=True, verbose_name='Project Status')),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated (e.g., Django, Python, Bootstrap)', max_length=500, verbose_name='Technologies')),
                ('is_featured', models.BooleanField(default=False, help_text='Homepage par show karna hai?', verbose_name='Featured Project')),
                ('order', models.IntegerField(default=0, help_text='Lower number appears first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Service Title')),
                ('short_description', models.CharField(blank=True, default='Short Description', max_length=255, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Full Description')),
                ('details', models.TextField(blank=True, help_text='Each point on a new line', verbose_name='Service Details')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class (e.g., fa-code) or emoji', max_length=80, verbose_name='Icon Class')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Service Image')),
                ('link', models.URLField(blank=True, verbose_name='Service Link')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Category')),
                ('duration', models.CharField(blank=True, help_text='e.g., 2-4 weeks', max_length=80, verbose_name='Duration')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('visible', models.BooleanField(default=True, verbose_name='Show on Website')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
