# Generated by Django 5.2.5 on 2025-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_level',
            field=models.CharField(choices=[('hs', 'Primary & Secondary '), ('hs', 'Higher Secondary '), ('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('cert', 'Certification'), ('other', 'Other')], default='other', max_length=12, verbose_name='Degree Level'),
        ),
    ]
